// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnyoRN3AKZp7hKBXIU1-wVMmG9fHjDvQ',
    appId: '1:341761700799:web:79e0a1efa4ca3ea5d2e70a',
    messagingSenderId: '341761700799',
    projectId: 'quizgame-2895e',
    authDomain: 'quizgame-2895e.firebaseapp.com',
    storageBucket: 'quizgame-2895e.appspot.com',
    measurementId: 'G-FSSM132M0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mOBCFPI7xn73HQ2uGpa7c8YTRcUifDg',
    appId: '1:341761700799:android:535def131997f0c6d2e70a',
    messagingSenderId: '341761700799',
    projectId: 'quizgame-2895e',
    storageBucket: 'quizgame-2895e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC3GL_60-lN_tOo4PgmtnSfJUyN5cOia4',
    appId: '1:341761700799:ios:0da69c42d9e89f18d2e70a',
    messagingSenderId: '341761700799',
    projectId: 'quizgame-2895e',
    storageBucket: 'quizgame-2895e.appspot.com',
    iosClientId: '341761700799-gtl38q20mfvrjh990qc03otcq3d61kl4.apps.googleusercontent.com',
    iosBundleId: 'com.quizgame.quizGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC3GL_60-lN_tOo4PgmtnSfJUyN5cOia4',
    appId: '1:341761700799:ios:0da69c42d9e89f18d2e70a',
    messagingSenderId: '341761700799',
    projectId: 'quizgame-2895e',
    storageBucket: 'quizgame-2895e.appspot.com',
    iosClientId: '341761700799-gtl38q20mfvrjh990qc03otcq3d61kl4.apps.googleusercontent.com',
    iosBundleId: 'com.quizgame.quizGame',
  );
}
